# Generated by Django 4.2.1 on 2023-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_model',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
