# Generated by Django 4.2.1 on 2023-05-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter',
            old_name='transporter_first_name',
            new_name='transporter_name',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='transporter_last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='transporter_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.transporter'),
        ),
    ]
