# Generated by Django 4.2.1 on 2023-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_item_model_item_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
