# Generated by Django 3.0.7 on 2023-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230511_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
