# Generated by Django 4.2.1 on 2023-05-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_transporter_first_name_transporter_transporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transporter_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.transporter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transporter_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
