# Generated by Django 4.2.1 on 2023-05-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_transporter_id_alter_order_transporter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transporter_name',
        ),
    ]
