# Generated by Django 4.2.1 on 2023-05-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_item_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_id',
        ),
    ]
