# Generated by Django 4.2.1 on 2023-05-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_first_name_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.transporter'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
