# Generated by Django 4.2.1 on 2023-05-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
