# Generated by Django 4.2.1 on 2023-05-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_transporter_alter_transporter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
