# Generated by Django 4.2.1 on 2023-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_order_item_remove_order_transporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
