# Generated by Django 4.2.1 on 2023-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_order_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
