# Generated by Django 4.2.1 on 2023-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_receiver_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_code',
            field=models.CharField(default=0, max_length=32, unique=True),
        ),
    ]
