# Generated by Django 4.2.1 on 2023-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal User')], default=0, max_length=10),
        ),
    ]
