# Generated by Django 3.0.7 on 2023-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230512_1519'),
        ('base', '0014_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
    ]
